# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=10000)),
                ('message_users', models.CharField(max_length=200)),
                ('message_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
